name: CageCollection
version: '1.0.0'
main: dev.ev1dent.cagecollection.CCMain
api-version: '1.20'
commands:
  cage:
    aliases:
      - spawners
      - cages
      - spawner
    usage: /<command> <give/set> <player> <mob>
